### ISSUE TITLE
Is there any idea about how to disable fcitx5 in konsole

### ISSUE THREAD

**Issue by Sharelter** [tonyfettes/fcitx5.nvim#3]
THX for your awesome project :)
U mentioned that this only work when fcitx5 disabled on terminal or gui,
but I didn't figured out how to archieve this.

Is there any idea or suggestion for it :)

**Comment by tonyfettes** [comment]
You're welcome!

Hmmm...I'm not familiar with konsole, but I guess it's using qt frontend instead of wayland frontend, so you can either disable fcitx5 in all qt applications or none. Therefore, I guess there is no way for you to use this plugin, if you still want to use fcitx5 in other qt applications? :(

I would suggest you to try to use this plugin instead. It is actively developed, and I think it can solve your problem.  But I haven't personally tried this plugin, so I'm not sure.
https://github.com/black-desk/fcitx5-ui.nvim

**Comment by Sharelter** [comment]
THX for your help ~
